export const clientConstants = {
  FETCH_CLIENTS_REQUEST: 'FETCH_CLIENTS_REQUEST',
  FETCH_CLIENTS_SUCCESS: 'FETCH_CLIENTS_SUCCESS',
  FETCH_CLIENTS_ERROR: 'FETCH_CLIENTS_ERROR',

  FETCH_CLIENT_TYPES_REQUEST: 'FETCH_CLIENT_TYPES_REQUEST',
  FETCH_CLIENT_TYPES_SUCCESS: 'FETCH_CLIENT_TYPES_SUCCESS',
  FETCH_CLIENT_TYPES_ERROR: 'FETCH_CLIENT_TYPES_ERROR',

  SET_CURRENT_CLIENT: 'SET_CURRENT_CLIENT',
};
