export const currencyConstants = {
  FETCH_CURRENCIES_REQUEST: "FETCH_CURRENCIES_REQUEST",
  FETCH_CURRENCIES_SUCCESS: "FETCH_CURRENCIES_SUCCESS",
  FETCH_CURRENCIES_ERROR: "FETCH_CURRENCIES_ERROR",
};
