export const hotelConstants = {
  FETCH_HOTELS_REQUEST: "FETCH_HOTELS_REQUEST",
  FETCH_HOTELS_SUCCESS: "FETCH_HOTELS_SUCCESS",
  FETCH_HOTELS_ERROR: "FETCH_HOTELS_ERROR",

  FETCH_ROOM_TYPES_REQUEST: "FETCH_ROOM_TYPES_REQUEST",
  FETCH_ROOM_TYPES_SUCCESS: "FETCH_ROOM_TYPES_SUCCESS",
  FETCH_ROOM_TYPES_ERROR: "FETCH_ROOM_TYPES_ERROR",

  FETCH_CHAINS_REQUEST: "FETCH_CHAINS_REQUEST",
  FETCH_CHAINS_SUCCESS: "FETCH_CHAINS_SUCCESS",
  FETCH_CHAINS_ERROR: "FETCH_CHAINS_ERROR",


  CREATE_NEW_HOTEL_REQUEST: "CREATE_NEW_HOTEL_REQUEST",
  CREATE_NEW_HOTEL_SUCCESS: "CREATE_NEW_HOTEL_SUCCESS",
  CREATE_NEW_HOTEL_ERROR: "CREATE_NEW_HOTEL_ERROR",
};
