export const hotelsConstants = {
  FETCH_HOTELS_REQUEST: "FETCH_HOTELS_REQUEST",
  FETCH_HOTELS_SUCCESS: "FETCH_HOTELS_SUCCESS",
  FETCH_HOTELS_ERROR: "FETCH_HOTELS_ERROR",

  FETCH_ROOM_TYPES_REQUEST: "FETCH_ROOM_TYPES_REQUEST",
  FETCH_ROOM_TYPES_SUCCESS: "FETROOM_TYPESELS_SUCCESS",
  FETCH_ROOM_TYPES_ERROR: "FETCH_HOTROOM_TYPESROR",
};
