export const rateConstants = {
  FETCH_RATES_REQUEST: "FETCH_RATES_REQUEST",
  FETCH_RATES_SUCCESS: "FETCH_RATES_SUCCESS",
  FETCH_RATES_ERROR: "FETCH_RATES_ERROR",
  FETCH_RATES_TYPES_SUCCESS: "FETCH_RATES_TYPES_SUCCESS",
  FETCH_RATES_STATES_SUCCESS: "FETCH_RATES_STATES_SUCCESS"
}