export const sharedConstants = {
  FETCH_COUNTRIES_REQUEST: "FETCH_COUNTRIES_REQUEST",
  FETCH_COUNTRIES_SUCCESS: "FETCH_COUNTRIES_SUCCESS",
  FETCH_COUNTRIES_ERROR: "FETCH_COUNTRIES_ERROR",

  //REGIONS
  FETCH_REGIONS_REQUEST: "FETCH_REGIONS_REQUEST",
  FETCH_REGIONS_SUCCESS: "FETCH_REGIONS_SUCCESS",
  FETCH_REGIONS_ERROR: "FETCH_REGIONS_ERROR",
};
