export const sharedConstants = {
  FETCH_COUNTRIES_REQUEST: "FETCH_COUNTRIES_REQUEST",
  FETCH_COUNTRIES_SUCCESS: "FETCH_COUNTRIES_SUCCESS",
  FETCH_COUNTRIES_ERROR: "FETCH_COUNTRIES_ERROR",

  //Provinces
  FETCH_PROVINCES_REQUEST: "FETCH_PROVINCES_REQUEST",
  FETCH_PROVINCES_SUCCESS: "FETCH_PROVINCES_SUCCESS",
  FETCH_PROVINCES_ERROR: "FETCH_PROVINCES_ERROR",
};
