export const userConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_WELCOME: "LOGIN_WELCOME",

  CLEAR_LOGIN_ERROR: "CLEAR_LOGIN_ERROR",
  LOGOUT: "USERS_LOGOUT",

  GET_USER_REQUEST: "GET_USER_REQUEST",
  GET_USER_SUCCESS: "GET_USER_SUCCESS",
  GET_USER_ERROR: "GET_USER_ERROR",

  GETALL_REQUEST: "USERS_GETALL_REQUEST",
  GETALL_SUCCESS: "USERS_GETALL_SUCCESS",
  GETALL_FAILURE: "USERS_GETALL_FAILURE",

  SET_USER_GROUP: "SET_USER_GROUP",
  CLEAR_USER_GROUP: "CLEAR_USER_GROUP",

  SHOW_CONTENT_AS_IN_HOTEL: "SHOW_CONTENT_AS_IN_HOTEL",
};
